### PR TITLE
Feature/wnb 107/implementation signin signup screens

### PR DESCRIPTION
**Pull request by vitali-sakalou**
Refactoring sign-in sign-up pages - routes and styles

### CODE REVIEW

**Review by ikushlianski — APPROVED** [review]
Please merge this pull, because other guys are away during these 5 days. I will merge your changes with mine in #12 and resolve conflicts. Thus we will have a more or less working routing system!

**Comment by ikushlianski** [comment]
Vitali, I meant merge this pull, not #12. I will revert that one, because otherwise you will have conflicts in this pull.

**Comment by ikushlianski** [comment]
We only should merge the pull requests that we ourselves opened. Merge other's pulls only if they explicitly ask, ok?)

**Comment by ikushlianski** [comment]
I reverted #12. Please merge your (#14) into develop first. Then I will resolve conflicts in #12 myself and merge #12 into develop.

**Comment by ikushlianski** [comment]
And please delete branches after you merge, so we don't clutter our repo

**Comment by vitali-sakalou** [comment]
Sorry for that) I am still try to up-to-date my experiance in git flow. Is it ok now?

**Comment by ikushlianski** [comment]
It's fine, no worries

**Pull request merged**
